app = 'eth-fund-transfer-server'
primary_region = 'sin'
swap_size_mb = 512

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 5001 
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
